[package]
name = "parsable"
version = "0.1.0"
edition = "2024"

[dependencies]
parsable-derive = { path = "parsable-derive" }
serde = { version = "1.0.228", features = ["derive"]}

[features]
parsable_debug = []
